


Eigen::VectorXd optimize_QP(Eigen::Matrix<double, 3, 7> J_70_l, 
			    Eigen::Matrix<double, 3, 7> J_70_dot_l,
		            Eigen::Matrix<double, 1, 7> J_70_l_proj_Xerr,
		            Eigen::Matrix<double, 1, 7> J_70_l_proj_x_axis,
		            Eigen::Matrix<double, 1, 7> J_70_l_proj_y_axis,		                    
		            Eigen::Matrix<double, 1, 7> J_70_l_proj_z_axis,
			    Eigen::Matrix<double, 1, 7> J_70_dot_l_proj_Xerr,
			    Eigen::Matrix<double, 1, 7> J_70_dot_l_proj_x_axis,			                
			    Eigen::Matrix<double, 1, 7> J_70_dot_l_proj_y_axis,			                
			    Eigen::Matrix<double, 1, 7> J_70_dot_l_proj_z_axis,	
                            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> M, 
                            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> M_inv, 
			    Eigen::Matrix<double, 7, 1> b,
			    Eigen::Matrix<double, 3, 1> Jdot_qdot_r_77,
			    Eigen::Matrix<double, 3, 1> Jdot_qdot_r_70,
			    Eigen::Matrix<double, 3, 1> Jdot_qdot_l,
		            Eigen::Matrix<double, 6, 1> Jdot_qdot,
			    Eigen::VectorXd X_err,
			    Eigen::VectorXd X_err_obst,
			    Eigen::VectorXd X_err_integal,
			    Eigen::VectorXd X_err_integal_obst,
       			    double X_err_integal_obst_Ec_lim,
			    Eigen::VectorXd V_err,
			    Eigen::VectorXd X_err_angle_prj, 
			    Eigen::VectorXd V_err_angle_prj,
			    Eigen::Twistd   V_7,
			    Eigen::VectorXd V_7_obst,
                            Eigen::VectorXd Acc_posi_70,
                            Eigen::VectorXd Acc_posi_70_prev,
                            Eigen::VectorXd Acc_posi_70_obst,
                            Eigen::VectorXd Acc_posi_70_prev_obst,
			    Eigen::VectorXd V_7_posi,
			    Eigen::Twistd   V_77,
			    Eigen::VectorXd V_7_des,
			    Eigen::VectorXd Acc_7_des,
			    Eigen::VectorXd Acc_7_orient_des,
                            double kp,
			    double kd, 
		            double d_safe,
			    double d_max, 
			    double E_safe,
                            double Ec_max_7,
			    Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> J_70,
		      	    Eigen::Matrix<double, 1, 7> J_70_C_proj,
		      	    Eigen::Matrix<double, 1, 7> J_70_C_dot_proj,
                            double dt,			  
                            double m_eq_7_j,
                            double m_eq_7_j_prev,
                            double m_eq_7_j_Xerr,
                            double m_eq_7_j_Xerr_prev,
                            double m_eq_7_j_Xerr_real_prev,
			    double m_eq_7_j_x_axis,			                
			    double m_eq_7_j_y_axis,	
			    double m_eq_7_j_z_axis,	
			    Eigen::Matrix<double, 7, 1> q_dotdot_bounds,
			    Eigen::Matrix<double, 7, 1> q_dotdot_bounds_max,
			    Eigen::Matrix<double, 7, 1> q_dotdot_bounds_min,
			    Eigen::Matrix<double, 7, 1> q_dotdot_bounds_max_comp,
			    Eigen::Matrix<double, 7, 1> q_dotdot_bounds_min_comp,
			    double dist_07_nrst_ob,
			    Eigen::Matrix<double, 7, 1> gravity_terms,
			    Eigen::Matrix<double, 3, 7> J_77_r,
  			    Eigen::VectorXd Acc_7_orient,
			    Eigen::VectorXd Acc_7, 
			    Eigen::VectorXd V_7_posi_proj,
                            Eigen::Displacementd H_disp_70, 
                            Eigen::Matrix<double, 3, 7> J_70_r, 
			    double nxt_step_des_Jerk_7_x, 	
		            double Jerk_x_curr, 
			    Eigen::Matrix<double, 7, 1> q,
			    Eigen::Matrix<double, 7, 1> q_dot,
			    Eigen::VectorXd q_ddot, 
			    Eigen::VectorXd q_dddot, 
			    Eigen::VectorXd q_ddddot,
			    Eigen::VectorXd q_bounds_min,
			    Eigen::VectorXd q_bounds_max,
			    Eigen::VectorXd q_dot_bounds_min,
			    Eigen::VectorXd q_dot_bounds_max,
			    Eigen::VectorXd q_dddot_bounds_min,
			    Eigen::VectorXd q_dddot_bounds_max,
                            Eigen::VectorXd q_dotdot_bounds_min_optimized,
                            Eigen::VectorXd q_dotdot_bounds_max_optimized, 
                            Eigen::Matrix<double, 7, 1> tau_min,
                            Eigen::Matrix<double, 7, 1> tau_max,
			    Eigen::VectorXd q_k2, 
			    Eigen::VectorXd q_ddot_k2,
			    Eigen::VectorXd q_dddot_k2,
			    Eigen::VectorXd q_ddddot_k2,
                            Eigen::Matrix<double, 7, 1> q_dotdot_bounds_max_prime_forwrd_backwrd, 
                            Eigen::Matrix<double, 7, 1> q_dotdot_bounds_min_prime_forwrd_backwrd,
			    double time_in_second, 
			    double time_in_micsecond, 
			    Eigen::VectorXd q_des_posture, 
 			    Eigen::VectorXd q_des, 
			    double E_7_C_ob, 
		            double Eta_proj_C, 
		            double nu_proj_C, 
		            double P_proj_C,
		            double Eta_proj_C_prev, 
		            double nu_proj_C_prev, 
		            double P_proj_C_prev);



